In [33]:
from Bio import SeqIO
import pandas as pd

sequences=[]
for sequence in SeqIO.parse('multifasta_WEL.fa', "fasta"):
    sequences.append(str(sequence.seq))


# cov2_sequences=[]
# for sequence in SeqIO.parse('cov2.fa', "fasta"):
#     cov2_sequences.append(sequence)

# infl_sequences=[]
# for sequence in SeqIO.parse('influenza.fa', "fasta"):
#     infl_sequences.append(sequence)   

# sars_sequences=[]
# for sequence in SeqIO.parse('sars.fa', "fasta"):
#     sars_sequences.append(sequence)   

GAATTCTCGAA


In [49]:
import numpy as np
import re

def string_to_array(seq_string):
   # print(seq_string)
   seq_string = seq_string.lower()
   seq_string = re.sub('[^acgt]', 'n', seq_string)
   seq_string = np.array(list(seq_string))
   return seq_string
# create a label encoder with 'acgtn' alphabet
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoder.fit(np.array(['a','c','g','t','n']))

LabelEncoder()

In [50]:
from sklearn.preprocessing import OneHotEncoder
def one_hot_encoder(seq_string):
    int_encoded = label_encoder.transform(seq_string)
    onehot_encoder = OneHotEncoder(sparse=False, dtype=int)
    int_encoded = int_encoded.reshape(len(int_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(int_encoded)
    onehot_encoded = np.delete(onehot_encoded, -1, 1)
    return onehot_encoded


In [52]:
x=sequences[0]
print(len(sequences[0]))
# x='GAATTCTCGAA'
print(one_hot_encoder(string_to_array(x)))


1416
[[0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [1 0 0 0]
 [0 0 1 0]]
