In [36]:
import numpy as np
bases={'A':np.array([0,0,0,1]), 'C':np.array([0,0,1,0]), 'G':np.array([0,1,0,0]), 'T':np.array([1,0,0,0]), 'N':np.array([0,0,0,0]), 'Y':np.array([0,0,0,0]), 'R':np.array([0,0,0,0]), 'W':np.array([0,0,0,0]), 'S':np.array([0,0,0,0]), 'K':np.array([0,0,0,0])}
k=4

def Kmers_funct(seq, size):
    return [seq[x:x+size].lower() for x in range(len(seq) - size + 1)]

def one_hot_encode_2(y,num_classes):
    y_encoded=[]
    for el in y:
        y_encoded.append(np.eye(num_classes)[el])
    return np.array(y_encoded)


In [40]:
from Bio import SeqIO
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()

unique_elems=dict()
x_data=[]
y_data=[]
minlen=100000
for sequence in SeqIO.parse('dataset.fasta', "fasta"):
    unique_elems[sequence.description.split()[1]+sequence.description.split()[2]]=0
    if len(sequence.seq)<minlen:
        minlen=len(sequence.seq)


i=0
for el in unique_elems.keys():
    unique_elems[el]=i
    i+=1

# print(unique_elems)
for sequence in SeqIO.parse('dataset.fasta', "fasta"):

    js=(' '.join(Kmers_funct(str(sequence.seq),k)))
    x_data.append(js)
    y_data.append(unique_elems[sequence.description.split()[1]+sequence.description.split()[2]])

print(len(x_data))
x=cv.fit_transform(x_data)
print(x.toarray())

x_data=x.toarray()
y_data=one_hot_encode_2(y_data,len(unique_elems))
print(x_data.shape)


118
[[ 3  5  8 ...  0  0  0]
 [ 3  5  9 ...  0  0  0]
 [ 3  5  9 ...  0  0  0]
 ...
 [ 3  9 12 ...  0  0  0]
 [ 3  9 12 ...  0  0  0]
 [ 3  9 12 ...  0  0  0]]
(118, 508)


In [38]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv1D, MaxPooling1D
from tensorflow.keras.callbacks import EarlyStopping

In [58]:
model=Sequential()

model.add(Dense(250, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(38, activation='relu'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(x_data, y_data, epochs=400, verbose=1, validation_data= None)

Epoch 1/400
4/4 [==============================] - 0s 14ms/step - loss: 10.3604 - accuracy: 0.0254
Epoch 2/400
4/4 [==============================] - 0s 6ms/step - loss: 9.8906 - accuracy: 0.0254
Epoch 3/400
4/4 [==============================] - 0s 6ms/step - loss: 9.8405 - accuracy: 0.0932
Epoch 4/400
1/4 [======>.......................] - ETA: 0s - loss: 8.6395 - accuracy: 0.1875

2021-12-30 17:57:04.371002: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


4/4 [==============================] - 0s 6ms/step - loss: 9.9982 - accuracy: 0.1610
Epoch 5/400
4/4 [==============================] - 0s 7ms/step - loss: 9.9496 - accuracy: 0.1356
Epoch 6/400
4/4 [==============================] - 0s 6ms/step - loss: 9.8919 - accuracy: 0.1356
Epoch 7/400
4/4 [==============================] - 0s 6ms/step - loss: 9.9476 - accuracy: 0.1356
Epoch 8/400
4/4 [==============================] - 0s 6ms/step - loss: 9.8951 - accuracy: 0.1356
Epoch 9/400
4/4 [==============================] - 0s 6ms/step - loss: 9.9471 - accuracy: 0.1356
Epoch 10/400
4/4 [==============================] - 0s 6ms/step - loss: 9.8923 - accuracy: 0.1949
Epoch 11/400
4/4 [==============================] - 0s 6ms/step - loss: 9.8132 - accuracy: 0.2542
Epoch 12/400
4/4 [==============================] - 0s 6ms/step - loss: 9.6347 - accuracy: 0.2966
Epoch 13/400
4/4 [==============================] - 0s 6ms/step - loss: 9.9559 - accuracy: 0.2542
Epoch 14/400
4/4 [====================